export const ARENA_SET_STATE = "ARENA_SET_STATE";
export const ARENA_REPLACE_STATE = "ARENA_REPLACE_STATE";
export const ARENA_LOAD_SCENE = "ARENA_LOAD_SCENE";
export const ARENA_LOAD_ASYNCSCENE = "ARENA_LOAD_ASYNCSCENE";
export const ARENA_HISTORY_PUSH = "ARENA_HISTORY_PUSH";

export const SCENE_SET_STATE = "SCENE_SET_STATE";
export const SCENE_REPLACE_STATE = "SCENE_REPLACE_STATE";
export const SCENE_LOAD_START = "SCENE_LOAD_START";
export const SCENE_LOAD_END = "SCENE_LOAD_END";
export const SCENE_PLAY_START = "SCENE_PLAY_START";
export const SCENE_PLAY_END = "SCENE_PLAY_END";

export const ARENA_INIT_AUDIENCE_SAGA = "ARENA_INIT_AUDIENCE_SAGA";
