export const ARENA_SET_STATE = "ARENA_SET_STATE";
export const ARENA_REPLACE_STATE = "ARENA_REPLACE_STATE";

export const SCENE_SET_STATE = "SCENE_SET_STATE";
export const SCENE_REPLACE_STATE = "SCENE_REPLACE_STATE";
export const SCENE_LOAD_START = "SCENE_LOAD_START";
export const SCENE_LOAD_END = "SCENE_LOAD_END";
export const SCENE_PLAY_START = "SCENE_PLAY_START";
export const SCENE_PLAY_END = "SCENE_PLAY_END";
export const SCENE_CLEAR_REDUX = "SCENE_CLEAR_REDUX";

export const ARENASWITCH_INIT_SAGA = "ARENASWITCH_INIT_SAGA";
export const ARENASWITCH_KILL_SAGA = "ARENASWITCH_KILL_SAGA";
export const ARENASWITCH_SET_STATE = "ARENASWITCH_SET_STATE";
export const ARENASWITCH_REPLACE_STATE = "ARENASWITCH_REPLACE_STATE";
export const ARENASWITCH_SWITCH_SCENE = "ARENASWITCH_SWITCH_SCENE";
export const ARENASWITCH_LOAD_ASYNCSCENE = "ARENASWITCH_LOAD_ASYNCSCENE";

export const ARENA_INIT_AUDIENCE_SAGA = "ARENA_INIT_AUDIENCE_SAGA";
