export const ARENA_SET_STATE = "ARENA_SET_STATE";
export const ARENA_REPLACE_STATE = "ARENA_REPLACE_STATE";

export const SCENE_SET_STATE = "SCENE_SET_STATE";
export const SCENE_REPLACE_STATE = "SCENE_REPLACE_STATE";
export const SCENE_LOAD_START = "SCENE_LOAD_START";
export const SCENE_LOAD_END = "SCENE_LOAD_END";
export const SCENE_PLAY_START = "SCENE_PLAY_START";
export const SCENE_PLAY_END = "SCENE_PLAY_END";
export const SCENE_CLEAR_REDUX = "SCENE_CLEAR_REDUX";

export const SCENESWITCH_INIT_SAGA = "SCENESWITCH_INIT_SAGA";
export const SCENESWITCH_KILL_SAGA = "SCENESWITCH_KILL_SAGA";
export const SCENESWITCH_SET_STATE = "SCENESWITCH_SET_STATE";
export const SCENESWITCH_REPLACE_STATE = "SCENESWITCH_REPLACE_STATE";
export const SCENESWITCH_SWITCH_SCENE = "SCENESWITCH_SWITCH_SCENE";
export const SCENESWITCH_LOAD_ASYNCSCENE = "SCENESWITCH_LOAD_ASYNCSCENE";

export const ARENA_INIT_AUDIENCE_SAGA = "ARENA_INIT_AUDIENCE_SAGA";
