export { ARENA_SCENE_SET_STATE } from "../core/actionTypes";

export const ARENA_SCENEBUNDLE_LOAD_START = "ARENA_SCENEBUNDLE_LOAD_START";

export const ARENA_SCENEBUNDLE_PLAY_START = "ARENA_SCENEBUNDLE_PLAY_START";

export const ARENA_SCENEBUNDLE_UNMOUNT_START =
  "ARENA_SCENEBUNDLE_UNMOUNT_START";