export { ARENA_SCENE_SET_STATE } from "../core/actionTypes";

export const ARENA_SCENEBUNDLE_LOAD_START =
  "ARENA_SCENEBUNDLE_LOAD_START";

export const ARENA_SCENE_LOAD_WAITING =
  "ARENA_SCENE_LOAD_WAITING";

export const ARENA_SCENE_LOAD_CONTINUE =
  "ARENA_SCENE_LOAD_CONTINUE";

export const ARENA_SCENEBUNDLE_LOAD_COMPLETE =
  "ARENA_SCENEBUNDLE_LOAD_COMPLETE";

export const ARENA_SCENEBUNDLE_UNMOUNT_START =
  "ARENA_SCENEBUNDLE_UNMOUNT_START";
