export const ARENASWITCH_EVENT_LOADSCENE_START =
  "ARENASWITCH_EVENT_LOADSCENE_START";

export const ARENASWITCH_EVENT_LOADSCENE_CONTINUE =
  "ARENASWITCH_EVENT_LOADSCENE_CONTINUE";

export const ARENASWITCH_EVENT_LOADSCENE_COMPLETE =
  "ARENASWITCH_EVENT_LOADSCENE_COMPLETE";
