export const ARENA_SET_STATE = "ARENA_SET_STATE";
export const ARENA_REPLACE_STATE = "ARENA_REPLACE_STATE";

export const ARENA_SCENE_SET_STATE = "ARENA_SCENE_SET_STATE";
export const ARENA_SCENE_REPLACE_STATE = "ARENA_SCENE_REPLACE_STATE";

export const ARENA_CURTAIN_SET_STATE = "ARENA_CURTAIN_SET_STATE";
export const ARENA_CURTAIN_REPLACE_STATE = "ARENA_CURTAIN_REPLACE_STATE";
export const ARENA_CURTAIN_INIT_SAGA = "ARENA_CURTAIN_INIT_SAGA";
export const ARENA_CURTAIN_CLEAR_REDUX = "ARENA_CURTAIN_CLEAR_REDUX";
export const ARENA_CURTAIN_LOAD_SCENE = "ARENA_CURTAIN_LOAD_SCENE";

export const ARENA_INIT_AUDIENCE_SAGA = "ARENA_INIT_AUDIENCE_SAGA";

export const ARENA_GLOBAL_PROPSPICKER_LOCK = "ARENA_GLOBAL_PROPSPICKER_LOCK";

export const ARENA_STATETREE_NODE_ADD = "ARENA_STATETREE_NODE_ADD";
export const ARENA_STATETREE_NODE_DISABLE = "ARENA_STATETREE_NODE_DISABLE";
export const ARENA_STATETREE_NODE_DELETE = "ARENA_STATETREE_NODE_DELETE";
