export const ARENA_SET_STATE = "ARENA_SET_STATE";
export const ARENA_REPLACE_STATE = "ARENA_REPLACE_STATE";

export const ARENA_SCENE_SET_STATE = "ARENA_SCENE_SET_STATE";
export const ARENA_SCENE_REPLACE_STATE = "ARENA_SCENE_REPLACE_STATE";
export const ARENA_SCENE_LOAD_START = "ARENA_SCENE_LOAD_START";
export const ARENA_SCENE_LOAD_END = "ARENA_SCENE_LOAD_END";
export const ARENA_SCENE_PLAY_START = "ARENA_SCENE_PLAY_START";
export const ARENA_SCENE_PLAY_END = "ARENA_SCENE_PLAY_END";
export const ARENA_SCENE_CLEAR_REDUX = "ARENA_SCENE_CLEAR_REDUX";

export const ARENA_SWITCH_INIT_SAGA = "ARENA_SWITCH_INIT_SAGA";
export const ARENA_SWITCH_CLEAR_REDUX = "ARENA_SWITCH_CLEAR_REDUX";
export const ARENA_SWITCH_SET_STATE = "ARENA_SWITCH_SET_STATE";
export const ARENA_SWITCH_REPLACE_STATE = "ARENA_SWITCH_REPLACE_STATE";
export const ARENA_SWITCH_LOAD_SCENE = "ARENA_SWITCH_LOAD_SCENE";
export const ARENA_SWITCH_LOAD_ASYNCSCENE = "ARENA_SWITCH_LOAD_ASYNCSCENE";

export const ARENA_INIT_AUDIENCE_SAGA = "ARENA_INIT_AUDIENCE_SAGA";
