export const ARENA_SCENE_ANIMATION_NEXTPHRASE =
  "ARENA_SCENE_ANIMATION_NEXTPHRASE";
export const ARENA_SCENE_ANIMATION_LEAVING_START =
  "ARENA_SCENE_ANIMATION_LEAVING_START";
export const ARENA_SCENE_ANIMATION_LOAD_BUNDLE =
  "ARENA_SCENE_ANIMATION_LOAD_BUNDLE";
